openapi: 3.0.0
info:
  contact:
    email: diogo.hudson@gmail.com
    name: Diogo Hudson Dias
  description: Simple appointment API for testing purpose on financial charges.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: DR Manager - Financial API
  version: 1.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: http://localhost:5001/1.0.0
tags:
- description: Financial related endpoints
  name: financial
paths:
  /financial/charge:
    post:
      operationId: add_charge
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChargeData'
      responses:
        "201":
          description: Created
        "400":
          description: bad input parameter
        "403":
          description: Token is invalid.
      security:
      - bearerAuth: []
      summary: Calculate amount for appointment
      tags:
      - financial
      x-openapi-router-controller: drm_financial.controllers.financial_controller
components:
  schemas:
    Charge:
      description: Charge data
      properties:
        id:
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
          format: uuid
          type: string
          x-server-default: Unknown
          x-primary-key: true
        appointment_id:
          example: Patient full name
          type: string
          x-index: true
        amount:
          example: 200.0
          format: float
          type: number
      type: object
      x-tablename: charge
    ChargeData:
      description: Charge by appointment
      example:
        total_price: 425.0
        appointment_id: d290f1ee-6c54-4b01-90e6-d701748f0851
      properties:
        appointment_id:
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
          format: uuid
          type: string
        total_price:
          example: 425.0
          format: float
          type: number
      required:
      - appointment_id
      - total_price
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
      x-bearerInfoFunc: drm_financial.controllers.security_controller_.info_from_bearerAuth
