version: '3'
services:
    lamconnect:
      env_file:
        - .env
      container_name: lamconnect
      ports:
        - '5000:5000'
        - '20005:20005'
      build:
        context: .
        dockerfile: Dockerfile
      command: python -m debugpy --listen 0.0.0.0:20005 -m application
      image: lamconnect
      volumes:
        - './:/app'
      environment:
        FLASK_DEBUG: 1
        FLASK_APP: ./main.py