openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: http://localhost:5001/1.0.0
info:
  description: Simple appointment API for testing purpose on financial charges.
  version: "1.0.0"
  title: DR Manager - Financial API
  contact:
    email: diogo.hudson@gmail.com
    name: Diogo Hudson Dias
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: financial
    description: Financial related endpoints
paths:
  /financial/charge:
    post:
      security:
        - bearerAuth: []
      tags: [financial]
      summary: Calculate amount for appointment
      operationId: addCharge
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChargeData'
      responses:
        '201':
          description: Created
        '400':
          description: bad input parameter
        '403':
          description: Token is invalid.
components:
  securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: "JWT"
  schemas:
    Charge:
      x-tablename: charge
      description: Charge data
      type: object
      properties:
        id:
          type: string
          format: uuid
          x-server-default: Unknown
          x-primary-key: true
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        appointment_id:
          type: string
          x-index: true
          example: Patient full name
        amount:
          type: number
          format: float
          example: 200.00
    ChargeData:
      description: Charge by appointment
      type: object
      required:
        - appointment_id
        - total_price
      properties:
        appointment_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        total_price:
          type: number
          format: float
          example: 425.00
