# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from drm_appointment.models.base_model_ import Model
from drm_appointment.models.patient_referal_id import PatientReferalId
from drm_appointment.models.physician_referal_id import PhysicianReferalId
from drm_appointment import util

from drm_appointment.models.patient_referal_id import PatientReferalId  # noqa: E501
from drm_appointment.models.physician_referal_id import PhysicianReferalId  # noqa: E501


class AppointmentPostData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start_date=None, end_date=None, physician=None, patient=None, price=None):  # noqa: E501
        """AppointmentPostData - a model defined in OpenAPI

        :param start_date: The start_date of this AppointmentPostData.  # noqa: E501
        :type start_date: datetime
        :param end_date: The end_date of this AppointmentPostData.  # noqa: E501
        :type end_date: datetime
        :param physician: The physician of this AppointmentPostData.  # noqa: E501
        :type physician: PhysicianReferalId
        :param patient: The patient of this AppointmentPostData.  # noqa: E501
        :type patient: PatientReferalId
        :param price: The price of this AppointmentPostData.  # noqa: E501
        :type price: float
        """
        self.openapi_types = {
            "start_date": datetime,
            "end_date": datetime,
            "physician": PhysicianReferalId,
            "patient": PatientReferalId,
            "price": float,
        }

        self.attribute_map = {
            "start_date": "start_date",
            "end_date": "end_date",
            "physician": "physician",
            "patient": "patient",
            "price": "price",
        }

        self._start_date = start_date
        self._end_date = end_date
        self._physician = physician
        self._patient = patient
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> "AppointmentPostData":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AppointmentPostData of this AppointmentPostData.  # noqa: E501
        :rtype: AppointmentPostData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_date(self):
        """Gets the start_date of this AppointmentPostData.


        :return: The start_date of this AppointmentPostData.
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this AppointmentPostData.


        :param start_date: The start_date of this AppointmentPostData.
        :type start_date: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this AppointmentPostData.


        :return: The end_date of this AppointmentPostData.
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this AppointmentPostData.


        :param end_date: The end_date of this AppointmentPostData.
        :type end_date: datetime
        """

        self._end_date = end_date

    @property
    def physician(self):
        """Gets the physician of this AppointmentPostData.


        :return: The physician of this AppointmentPostData.
        :rtype: PhysicianReferalId
        """
        return self._physician

    @physician.setter
    def physician(self, physician):
        """Sets the physician of this AppointmentPostData.


        :param physician: The physician of this AppointmentPostData.
        :type physician: PhysicianReferalId
        """

        self._physician = physician

    @property
    def patient(self):
        """Gets the patient of this AppointmentPostData.


        :return: The patient of this AppointmentPostData.
        :rtype: PatientReferalId
        """
        return self._patient

    @patient.setter
    def patient(self, patient):
        """Sets the patient of this AppointmentPostData.


        :param patient: The patient of this AppointmentPostData.
        :type patient: PatientReferalId
        """

        self._patient = patient

    @property
    def price(self):
        """Gets the price of this AppointmentPostData.


        :return: The price of this AppointmentPostData.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this AppointmentPostData.


        :param price: The price of this AppointmentPostData.
        :type price: float
        """

        self._price = price
